Fix voice generator
pndurette/gTTS pull request #369
Opened 2022-11-02 22:32 UTC by ryan5453

Previously the gen_langs.py script was broken, so it wasn't possible to fetch new languages. I wasn't able to find an easy way to get the languages from the JavaScript files, so I decided to just test every Google Translate-supported language and see if it has a voice.

I ran the new script so the langs.py file will be updated.

2022-11-02 22:36 UTC, ryan5453 commented
Perhaps the script could be run via a GitHub Action on an interval (not sure what the best interval would be), not sure how you would want to handling bumping the version though.

2022-11-03 02:39 UTC, pndurette commented
Oh this is awesome!
The JavaScript route was always very janky and this is much much simpler—thanks!

> Perhaps the script could be run via a GitHub Action on an interval (not sure what the best interval would be), not sure how you would want to handling bumping the version though.

I was actually planning on doing this! As for the version bumping, actually I'm working on revamping the release process and use conventional commits to do automatic version bumps. Which was needed for this to truly work.

If you could actually revert that change to the jump, I'll do it outside of this PR. Thanks!

2022-11-03 02:40 UTC, pndurette requested changes

2022-11-03 02:40 UTC, pndurette commented on gtts/version.py
> +__version__ = "2.2.5"
The version will be bumped outside of this PR

2022-11-03 21:39 UTC, ryan5453 commented
All set.

2022-11-21 03:04 UTC, pndurette approved these changes

2022-11-21 03:10 UTC, merged

2022-12-21 05:24 UTC, pndurette commented
> Perhaps the script could be run via a GitHub Action on an interval (not sure what the best interval would be), not sure how you would want to handling bumping the version though.

Just implemented this!
With [scripts/gen_langs.py](scripts/gen_langs.py) to detect changes (and generating a commit message) and a workflow [.github/workflows/update_langs.yml](.github/workflows/update_langs.yml) to create a PR